-- Run this in your Supabase SQL Editor to create the articles table

CREATE TABLE IF NOT EXISTS articles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    title TEXT NOT NULL,
    source TEXT,
    date TEXT,
    content TEXT,
    full_text TEXT,
    url TEXT UNIQUE,
    image_url TEXT,
    category_hint TEXT,
    raw_json JSONB,
    summary TEXT,
    sentiment_label TEXT,
    sentiment_score FLOAT,
    bias_label TEXT,
    bias_score FLOAT,
    bias_breakdown JSONB,
    reliability_score FLOAT DEFAULT 0.5,
    category TEXT
);

-- Enable Row Level Security (RLS)
ALTER TABLE articles ENABLE ROW LEVEL SECURITY;

-- Create policy for public read access
CREATE POLICY "Allow public read access" ON articles
    FOR SELECT USING (true);

-- Create policy for service role/authenticated inserts (depending on your setup)
-- For this simple news app, we'll allow all authenticated users to insert/sync
CREATE POLICY "Allow authenticated inserts" ON articles
    FOR INSERT WITH CHECK (auth.role() = 'authenticated' OR auth.role() = 'anon');

-- Note: In production, you'd restrict INSERT to a service role or specific admin users.
